# Short Video - Product Ad with Speaker
# =====================================
# Professional product advertisement with presenter
# Clean, polished product showcase with voiceover
# Suitable for e-commerce, DTC brands, product launches

title: "Product Ad with Speaker"
aspect_ratio: "9:16"
resolution: "720p"

# Use Wan 2.5 I2V - cheap with audio support (durations: 5 or 10s only)
video_model: "wan-2.5-i2v"
image_model: "flux-2-pro"

# Product configuration
# Place product images in: products/{product_name}/
# - main.png (hero shot)
# - detail.png (close-up)
# - lifestyle.png (in-use)

scenes:
  # Scene 1: Product Reveal - attention grabbing intro
  # Duration: 5s = 11-14 words recommended
  - id: "reveal"
    type: "speaker"
    duration_s: 5

    script: "Introducing the product that everyone's been talking about. Let me show you why."
    # 13 words ^

    video_prompt: >
      Professional presenter in studio setting, confident smile,
      green screen background, clean lighting, polished look,
      product reveal energy, vertical 9:16 format,
      close-mic voiceover audio, clear speech, no room echo

    speaker_image: "speakers/speaker2.png"

    # product_image: "products/your_product/main.png"
    background_prompt: >
      Premium product photography setup, soft gradient background,
      elegant lighting, luxury brand aesthetic,
      product hero shot, vertical 9:16 format

    overlay_scale: 0.30
    overlay_position: "bottom_right"

  # Scene 2: Feature 1 - key benefit
  # Duration: 5s = 11-14 words recommended
  - id: "feature1"
    type: "speaker"
    duration_s: 5

    script: "First, the quality. Premium materials that you can feel the moment you touch it."
    # 14 words ^

    video_prompt: >
      Same presenter demonstrating quality, touching product,
      green screen background, appreciative expression,
      product demo style, vertical 9:16 format,
      close-mic voiceover audio, clear speech, no room echo

    speaker_image: "speakers/speaker2.png"

    # product_image: "products/your_product/detail.png"
    background_prompt: >
      Close-up product detail shot, texture focus,
      macro photography style, premium materials visible,
      quality showcase, vertical 9:16 format

    overlay_scale: 0.25
    overlay_position: "bottom_left"

  # Scene 3: Feature 2 - unique selling point
  # Duration: 5s = 11-14 words recommended
  - id: "feature2"
    type: "speaker"
    duration_s: 5

    script: "What makes it special? It solves the one problem others couldn't figure out."
    # 13 words ^

    video_prompt: >
      Same presenter with knowing expression, explaining benefit,
      green screen background, engaged storytelling,
      product education style, vertical 9:16 format,
      close-mic voiceover audio, clear speech, no room echo

    speaker_image: "speakers/speaker2.png"

    background_prompt: >
      Product in action, lifestyle context,
      showing the solution, clean aesthetic,
      benefit visualization, vertical 9:16 format

    overlay_scale: 0.30
    overlay_position: "top_right"

  # Scene 4: Social Proof - credibility
  # Duration: 5s = 11-14 words recommended (Wan requires 5 or 10s)
  - id: "social_proof"
    type: "speaker"
    duration_s: 5

    script: "Over ten thousand happy customers already. Five star reviews everywhere you look."
    # 13 words ^

    video_prompt: >
      Same presenter with proud expression, gesturing to reviews,
      green screen background, credibility moment,
      testimonial style, vertical 9:16 format,
      close-mic voiceover audio, clear speech, no room echo

    speaker_image: "speakers/speaker2.png"

    background_prompt: >
      Five star review graphics, happy customer aesthetic,
      trust badges, social proof visualization,
      credibility showcase, vertical 9:16 format

    overlay_scale: 0.35
    overlay_position: "bottom_center"

  # Scene 5: Offer + CTA - drive action
  # Duration: 5s = 11-14 words recommended (Wan requires 5 or 10s)
  - id: "offer_cta"
    type: "speaker"
    duration_s: 5

    script: "Get twenty percent off today only. Tap the link below right now!"
    # 13 words ^

    video_prompt: >
      Same presenter with urgent but friendly expression,
      green screen background, pointing at camera,
      strong CTA energy, vertical 9:16 format,
      close-mic voiceover audio, clear speech, no room echo

    speaker_image: "speakers/speaker2.png"

    overlay_scale: 0.45
    overlay_position: "center"

    background_prompt: >
      Sale graphics with discount badge, urgency aesthetic,
      limited time offer vibe, premium but accessible,
      CTA moment, vertical 9:16 format
